name: 3dcertify
channels:
  - pytorch
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - python=3.8
  - gurobi=9.1.1
  - onnx=1.8.1
  - tensorboard=2.3.0
  - pytorch=1.6.0
  - cpuonly
  - torchvision=0.7.0
  - parameterized=0.8.1
  - deprecated=1.2.11
  - pip=20.3.3
  - tensorflow=2.3.0
  - pip:
    - h5py==3.1.0
    - matplotlib==3.3.4
    - onnxruntime==1.6.0
    - pandas==1.2.2
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.8
    - torch-geometric==1.6.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - tqdm==4.57.0
